### ISSUE TITLE
Accepting the pop-up after submit button leads to a blank dashboard page

### ISSUE THREAD

**Issue by madaanpulkit** [jhu-cs-ca-hiring/feedback#4]
### Is there an existing issue (report) for this bug?

- [X] I have searched the existing issues.

### What happened?

**Error**
Accepting the pop-up after submit button leads to a blank dashboard page

**Reproduction Steps**
1. Select Fall 22
2. Fill the form
3. Submit 
4. Accept Pop-up

Leads to blank Dashboard. Reloading the page shows Fall 22 as still unsubmitted.

### Additional details?

Error was spotted on 
Google Chrome: Version 101.0.4951.64 (Official Build) (x86_64)
Microsoft Edge: Version 102.0.1245.39 (Official build) (x86_64)

Screenshot of Developer Tools Console [Attached]
<img width="553" alt="Screenshot 2022-06-17 at 4 15 23 AM" src="https://user-images.githubusercontent.com/22029752/174190896-4d8c62fa-735e-4cb2-adbd-1e67130784d9.png">

### Contact details?

pmadaan2@jhu.edu

**Comment by madooei** [comment]
Thank you for reporting the issue! It must be fixed now :)

**Comment by madaanpulkit** [comment]
It does not lead to a blank page now and displays a pop-up informing about an error while submitting. The form still does not get submitted.

**Comment by madaanpulkit** [comment]
@madooei thanks for the fix It does not lead to a blank page now and displays a pop-up informing about an error while submitting. 
But the form still does not get submitted.

**Comment by madaanpulkit** [comment]
Found the error. Raising a new issue #5
